# Application name - identifies this service in the microservices architecture
spring.application.name=inventory-service

# Server port - the port on which this service will run
server.port=8083

# Eureka server URL - the address of the service discovery server for registration
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka

# Database URL - JDBC connection string to MySQL database
spring.datasource.url=jdbc:mysql://mysql:3306/inventory_db
# Database username - MySQL user for authentication
spring.datasource.username=root
# Database password - MySQL password for authentication
spring.datasource.password=root@123

# Hibernate DDL auto - automatically updates database schema based on entity classes (update = create/update tables)
spring.jpa.hibernate.ddl-auto=update
# Show SQL - logs SQL queries to console for debugging
spring.jpa.show-sql=true

# Kafka broker address - the location of the Kafka server
spring.kafka.bootstrap-servers=kafka:9092
# Consumer group ID - identifies the consumer group this service belongs to
spring.kafka.consumer.group-id=inventory-group
# Auto offset reset - determines where to start reading if no offset is committed (earliest = from beginning, latest = from newest)
spring.kafka.consumer.auto-offset-reset=earliest
# Key deserializer - converts message keys from bytes to String format
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
# Value deserializer - converts message values from bytes to JSON format
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
# Trusted packages - allows deserialization of JSON from all packages (*) for security
spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.kafka.consumer.properties.spring.json.value.default.type=com.umeshrc.inventory_service.dto.OrderCreatedEvent

spring.kafka.consumer.properties.spring.json.use.type.headers=false