# Application Name
spring.application.name=notification-service

# Server Port
server.port=8084

# Eureka Registration
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka

# Kafka Configuration
spring.kafka.bootstrap-servers=kafka:9092

# Consumer Group
spring.kafka.consumer.group-id=notification-group

# Read old messages if no offset exists
spring.kafka.consumer.auto-offset-reset=earliest

# Key Deserializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Value Deserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Trust Packages
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Use Notification DTO
spring.kafka.consumer.properties.spring.json.value.default.type=com.umeshrc.notification_service.dto.OrderCreatedEvent

# Ignore Producer DTO package
spring.kafka.consumer.properties.spring.json.use.type.headers=false